/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models

import ch.unibas.dmi.dbis.cineast.client.models.MediaObjectDescriptor
import ch.unibas.dmi.dbis.cineast.client.models.MediaObjectMetadataDescriptor

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `object` 
 * @param metadata 
 * @param uri 
 */

data class ExtractionItemContainer (

    @field:JsonProperty("object")
    val `object`: MediaObjectDescriptor? = null,

    @field:JsonProperty("metadata")
    val metadata: kotlin.collections.List<MediaObjectMetadataDescriptor>? = null,

    @field:JsonProperty("uri")
    val uri: kotlin.String? = null

)

