/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param objectid 
 * @param name 
 * @param path 
 * @param mediatype 
 * @param exists 
 * @param contentURL 
 */

data class MediaObjectDescriptor (

    @field:JsonProperty("objectid")
    val objectid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("path")
    val path: kotlin.String? = null,

    @field:JsonProperty("mediatype")
    val mediatype: MediaObjectDescriptor.Mediatype? = null,

    @field:JsonProperty("exists")
    val exists: kotlin.Boolean? = null,

    @field:JsonProperty("contentURL")
    val contentURL: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: VIDEO,IMAGE,AUDIO,MODEL3_D,IMAGE_SEQUENCE,UNKNOWN
     */
    enum class Mediatype(val value: kotlin.String) {
        @JsonProperty(value = "VIDEO") VIDEO("VIDEO"),
        @JsonProperty(value = "IMAGE") IMAGE("IMAGE"),
        @JsonProperty(value = "AUDIO") AUDIO("AUDIO"),
        @JsonProperty(value = "MODEL3D") MODEL3_D("MODEL3D"),
        @JsonProperty(value = "IMAGE_SEQUENCE") IMAGE_SEQUENCE("IMAGE_SEQUENCE"),
        @JsonProperty(value = "UNKNOWN") UNKNOWN("UNKNOWN");
    }
}

