/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param segmentId 
 * @param objectId 
 * @param start 
 * @param end 
 * @param startabs 
 * @param endabs 
 * @param count 
 * @param sequenceNumber 
 */

data class MediaSegmentDescriptor (

    @field:JsonProperty("segmentId")
    val segmentId: kotlin.String? = null,

    @field:JsonProperty("objectId")
    val objectId: kotlin.String? = null,

    @field:JsonProperty("start")
    val start: kotlin.Int? = null,

    @field:JsonProperty("end")
    val end: kotlin.Int? = null,

    @field:JsonProperty("startabs")
    val startabs: kotlin.Float? = null,

    @field:JsonProperty("endabs")
    val endabs: kotlin.Float? = null,

    @field:JsonProperty("count")
    val count: kotlin.Int? = null,

    @field:JsonProperty("sequenceNumber")
    val sequenceNumber: kotlin.Int? = null

)

