/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param segmentid 
 * @param domain 
 * @param key 
 * @param `value` 
 * @param exists 
 * @param segmentId 
 */

data class MediaSegmentMetadataDescriptor (

    @field:JsonProperty("segmentid")
    val segmentid: kotlin.String? = null,

    @field:JsonProperty("domain")
    val domain: kotlin.String? = null,

    @field:JsonProperty("key")
    val key: kotlin.String? = null,

    @field:JsonProperty("value")
    val `value`: kotlin.String? = null,

    @field:JsonProperty("exists")
    val exists: kotlin.Boolean? = null,

    @field:JsonProperty("segmentId")
    val segmentId: kotlin.String? = null

)

