/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param domain 
 * @param key 
 */

data class MetadataAccessSpecification (

    @field:JsonProperty("type")
    val type: MetadataAccessSpecification.Type? = null,

    @field:JsonProperty("domain")
    val domain: kotlin.String? = null,

    @field:JsonProperty("key")
    val key: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: OBJECT,SEGMENT
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "OBJECT") OBJECT("OBJECT"),
        @JsonProperty(value = "SEGMENT") SEGMENT("SEGMENT");
    }
}

