/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param categories 
 * @param type 
 * @param `data` 
 */

data class QueryTerm (

    @field:JsonProperty("categories")
    val categories: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("type")
    val type: QueryTerm.Type,

    @field:JsonProperty("data")
    val `data`: kotlin.String

) {

    /**
     * 
     *
     * Values: IMAGE,AUDIO,MODEL3_D,LOCATION,PARAMETERISED_LOCATION,TIME,TEXT,TAG,SEMANTIC,SKELETON,ID,BOOLEAN
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "IMAGE") IMAGE("IMAGE"),
        @JsonProperty(value = "AUDIO") AUDIO("AUDIO"),
        @JsonProperty(value = "MODEL3D") MODEL3_D("MODEL3D"),
        @JsonProperty(value = "LOCATION") LOCATION("LOCATION"),
        @JsonProperty(value = "PARAMETERISED_LOCATION") PARAMETERISED_LOCATION("PARAMETERISED_LOCATION"),
        @JsonProperty(value = "TIME") TIME("TIME"),
        @JsonProperty(value = "TEXT") TEXT("TEXT"),
        @JsonProperty(value = "TAG") TAG("TAG"),
        @JsonProperty(value = "SEMANTIC") SEMANTIC("SEMANTIC"),
        @JsonProperty(value = "SKELETON") SKELETON("SKELETON"),
        @JsonProperty(value = "ID") ID("ID"),
        @JsonProperty(value = "BOOLEAN") BOOLEAN("BOOLEAN");
    }
}

