/**
 * Cineast RESTful API
 *
 * Cineast is vitrivr's content-based multimedia retrieval engine. This is it's RESTful API.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@vitrivr.org
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ch.unibas.dmi.dbis.cineast.client.models

import ch.unibas.dmi.dbis.cineast.client.models.TemporalObject

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param queryId 
 * @param content 
 * @param messageType 
 */

data class TemporalQueryResult (

    @field:JsonProperty("queryId")
    val queryId: kotlin.String? = null,

    @field:JsonProperty("content")
    val content: kotlin.collections.List<TemporalObject>? = null,

    @field:JsonProperty("messageType")
    val messageType: TemporalQueryResult.MessageType? = null

) {

    /**
     * 
     *
     * Values: PING,Q_SIM,Q_MLT,Q_NESEG,Q_SEG,Q_TEMPORAL,SESSION_INFO,QR_START,QR_END,QR_ERROR,QR_OBJECT,QR_METADATA_O,QR_METADATA_S,QR_SEGMENT,QR_SIMILARITY,QR_TEMPORAL
     */
    enum class MessageType(val value: kotlin.String) {
        @JsonProperty(value = "PING") PING("PING"),
        @JsonProperty(value = "Q_SIM") Q_SIM("Q_SIM"),
        @JsonProperty(value = "Q_MLT") Q_MLT("Q_MLT"),
        @JsonProperty(value = "Q_NESEG") Q_NESEG("Q_NESEG"),
        @JsonProperty(value = "Q_SEG") Q_SEG("Q_SEG"),
        @JsonProperty(value = "Q_TEMPORAL") Q_TEMPORAL("Q_TEMPORAL"),
        @JsonProperty(value = "SESSION_INFO") SESSION_INFO("SESSION_INFO"),
        @JsonProperty(value = "QR_START") QR_START("QR_START"),
        @JsonProperty(value = "QR_END") QR_END("QR_END"),
        @JsonProperty(value = "QR_ERROR") QR_ERROR("QR_ERROR"),
        @JsonProperty(value = "QR_OBJECT") QR_OBJECT("QR_OBJECT"),
        @JsonProperty(value = "QR_METADATA_O") QR_METADATA_O("QR_METADATA_O"),
        @JsonProperty(value = "QR_METADATA_S") QR_METADATA_S("QR_METADATA_S"),
        @JsonProperty(value = "QR_SEGMENT") QR_SEGMENT("QR_SEGMENT"),
        @JsonProperty(value = "QR_SIMILARITY") QR_SIMILARITY("QR_SIMILARITY"),
        @JsonProperty(value = "QR_TEMPORAL") QR_TEMPORAL("QR_TEMPORAL");
    }
}

